1.13. Работаем с условиями
htmlacademy-php/147450-yeticave-12 pull request #1
Opened 2021-04-30 10:33 UTC by Petrusia

2021-05-11 05:08 UTC, olegmifle requested changes

2021-05-11 05:08 UTC, olegmifle commented on functions/validation.php
> +}
Зачем это?

2021-05-11 05:08 UTC, olegmifle commented on functions/validation.php
> +function validateString(string $field, string $errMessage)
Нужно типизировать результат работы функции. Этой и всех остальных

2021-05-11 05:08 UTC, olegmifle commented on functions/validation.php
> +<?php
Много "велосипедов" придумал. Но если представить, что этот файл с функциями нужен, то что делают среди валидаторов getLotInput, getImage? Они ничего не проверяют

2021-05-11 19:24 UTC, Petrusia commented on functions/validation.php
> +}
Я просто назвал его по-другому, чтобы сократить имя

Способы защиты от XSS
http://phpdemo.ru/?type=php#/example/03/module/3
function esc($str) {
	$text = htmlspecialchars($str);
	//$text = strip_tags($str);

	return $text;
}

2021-05-11 19:26 UTC, Petrusia commented on functions/validation.php
> +function validateString(string $field, string $errMessage)
тут функция возвращает или false  или string. Так возвращать пустую сторку вместо false ?

2021-05-11 19:29 UTC, Petrusia commented on functions/validation.php
> +function validateString(string $field, string $errMessage)
Поправил

2021-05-12 17:09 UTC, olegmifle commented on functions/validation.php
> +}
Лучше так не делать т.к. никакой полезной нагрузки нет, а htmlspecialchars всем известна, что бы понять, что за функция h нужно сходить и посмотреть. В общем, только запутаешь себя и других

2021-05-12 17:10 UTC, olegmifle commented on functions/validation.php
> +function validateString(string $field, string $errMessage)
Можно вернуть null, например. `): ?string`

2021-05-13 09:26 UTC, olegmifle commented on functions/config.php
> +const DB_NAME = 'yetidb';
Обычно лоины\пароли не хранят в гите :) 
Т.к. это тренировочный проект, может и ничего страшного, но на своих так делать нельзя никогда

2021-05-13 09:27 UTC, olegmifle commented on functions/validation.php
>      if ($period <= 86400) {
Тако лучше в константу выносить, т.к. 86400 выглядит не понятно.

2021-05-13 09:27 UTC, olegmifle commented on functions/validation.php
> +function validateImage($field, $errMessage): ?string
Параметры функций тоже нужно типизировать, по-хорошему.

2021-05-13 09:27 UTC, merged