Module7 task1
htmlacademy-php/147450-yeticave-12 pull request #2
Opened 2021-05-15 16:06 UTC by Petrusia

2021-05-17 05:07 UTC, olegmifle requested changes

2021-05-17 05:07 UTC, olegmifle commented on functions/validation.php
> +    if (isEmail($db, $field)) {
Не очень удачное название. Выглядит так, буд-то ты проверяешь email ли это вообще.

2021-05-17 05:07 UTC, olegmifle commented on functions/db.php
> +    $sql = "SELECT id FROM user WHERE email = ?";
```suggestion
    $sql = "SELECT count(id) FROM user WHERE email = ?";
```

2021-05-17 18:02 UTC, Petrusia commented on functions/db.php
> +    $sql = "SELECT id FROM user WHERE email = ?";
function isEmailExist(mysqli $db, string $email):bool
{
    $sql = "SELECT count(id) FROM user WHERE email = ?";
    $stmt = mysqli_prepare($db, $sql);
    mysqli_stmt_bind_param($stmt, 's', $email);
    mysqli_stmt_execute($stmt);
    $res = mysqli_stmt_get_result($stmt);
    if ($res->field_count > 0) {
        return true;
    }
    return false;
}

2021-05-18 05:04 UTC, olegmifle commented on functions/db.php
> +    return false;
```suggestion
    return count($result) > 0;
```

2021-06-15 08:55 UTC, merged